### ISSUE TITLE
Deploy site build fails: Cannot find module 'react' after prepare-script change

### ISSUE THREAD

**Issue by BlueVajra** [TheGuitarStudio/tonal-guitar#51]
## Summary

The "Deploy site" workflow (deploy.yml) has been failing on every push to main since commit 5f2a646, which added a `prepare` script to the root `package.json`. The "Build site" step fails with a TypeScript error that it cannot find the `react` module, even though no `site/` changes had landed at the time of the first failure.

## Details

- Failing run: https://github.com/TheGuitarStudio/tonal-guitar/actions/runs/28837126314
- First bad commit: `5f2a646` — "build: add prepare script so git-dependency installs build dist" — adds `"prepare": "npm run build"` to the root `package.json` scripts (intended so consumers pinning this repo as a git dependency get a built `dist/` via the npm lifecycle hook). It also fixed the repository URL (coryleistikow -> TheGuitarStudio). Only `package.json` changed in that commit (2 insertions, 1 deletion).
- It failed again on the very next push, `9c06e64` (feat: curated extended chord shapes import, #50), workflow run 28837126314, before any `site/` changes had landed — ruling out a site-specific regression as the sole cause.
- `ci.yml` continues to pass; only `deploy.yml` is affected, which points at something specific to the deploy workflow's install/build sequence (root `npm ci` → `npm run build` → `site` `npm ci` → `site` `npm run build`) rather than a general build break.
- Error excerpt from the failing "Build site" step:
  ```
  Failed to compile.
  Type error: Cannot find module 'react' or its corresponding type declarations.
  ##[error]Process completed with exit code 1.
  ```
- Likely contributing factor (unconfirmed, needs investigation): `site/package.json` depends on `fretboard-ui` via `"file:../packages/fretboard-ui"`, and `packages/fretboard-ui/package.json` in turn has a devDependency `"tonal-guitar": "file:../.."` pointing back at the root package. With the new root `prepare` script (`npm run build`), installing/resolving this nested `file:` dependency chain during `site`'s `npm ci` may re-trigger the root build and/or change how npm hoists `react`/`@types/react` (a `site` devDependency), such that it's missing or unresolved by the time the Next.js build step type-checks. This needs someone to actually reproduce locally (e.g. `rm -rf node_modules site/node_modules packages/*/node_modules && npm ci && npm run build && cd site && npm ci && npm run build`) to confirm the mechanism before attempting a fix.

## Steps to Reproduce

1. Push to main (or re-run the "Deploy site" workflow)
2. Build site step fails with: Type error: Cannot find module 'react' or its corresponding type declarations
